package app.freerouting.board;

import app.freerouting.autoroute.AutorouteControl;
import app.freerouting.core.library.BoardLibrary;
import app.freerouting.core.library.Padstack;
import app.freerouting.datastructures.ShapeTree.TreeEntry;
import app.freerouting.datastructures.UndoableObjects;
import app.freerouting.geometry.planar.Area;
import app.freerouting.geometry.planar.ConvexShape;
import app.freerouting.geometry.planar.IntBox;
import app.freerouting.geometry.planar.IntOctagon;
import app.freerouting.geometry.planar.Point;
import app.freerouting.geometry.planar.Polyline;
import app.freerouting.geometry.planar.PolylineShape;
import app.freerouting.geometry.planar.TileShape;
import app.freerouting.geometry.planar.Vector;
import app.freerouting.logger.FRLogger;
import app.freerouting.rules.BoardRules;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.security.MessageDigest;
import java.util.Collection;
import java.util.ConcurrentModificationException;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;

/**
 * Provides basic functionality of a board with geometric items. It contains functions such as
 * inserting, deleting, modifying and picking items and elementary checking functions. A board may
 * have one or several layers.
 */
public class BasicBoard implements Serializable {

  /**
   * The maximum number of outer-loop iterations in {@link #normalizeTraces}. Each legitimate
   * split/combine operation converges the board toward a stable state, so a well-formed net needs
   * at most a small multiple of its trace count. If we exceed this bound we are almost certainly
   * oscillating (split → combine → split …) and must break out.
   */
  private static final int MAX_NORMALIZE_ITERATIONS = 2000;

  /**
   * List of items inserted into this board (e.g. trace classes). Traces are Item classes that
   * implement the Connectable interface.
   */
  public final UndoableObjects itemList;

  /** List of placed components on the board. */
  public final Components components;

  /**
   * Class defining the rules for items to be inserted into this board. Contains for example the
   * clearance matrix.
   */
  public final BoardRules rules;

  /** The library containing padstack masks, packages and other templates used on the board. */
  public final BoardLibrary library;

  /** The layer structure of this board. */
  public final LayerStructure layerStructure;

  /** For communication with a host system or host design file formats. */
  public final Communication communication;

  /** Bounding orthogonal rectangle of this board. */
  public final IntBox boundingBox;

  /** Handles the search trees pointing into the items of this board. */
  public transient SearchTreeManager searchTreeManager;

  private transient Set<Integer> normalizeSuppressedNetNos = new HashSet<>();
  private transient int revision;

  /** The rectangle, where the graphics may be not up-to-date. */
  private transient IntBox updateBox = IntBox.EMPTY;

  /** The biggest half width of all traces on the board. */
  private int maxTraceHalfWidth = 1000;

  /** The smallest half width of all traces on the board. */
  private int minTraceHalfWidth = 10000;

  /**
   * Creates a new instance of a routing Board with surrounding box p_bounding_box Rules contains
   * the restrictions to obey when inserting items. Among other things it may contain a clearance
   * matrix. p_observers is used for synchronisation, if the board is generated by a host database,
   * otherwise it is null. If p_test_level != RELEASE_VERSION, some features may be used, which are
   * still in experimental state. Warnings for debugging may be printed depending on the size of
   * p_test_level.
   */
  public BasicBoard(
      IntBox boundingBox,
      LayerStructure layerStructure,
      PolylineShape[] outlineShapes,
      int outlineClClassNo,
      BoardRules rules,
      Communication communication) {
    this.layerStructure = layerStructure;
    this.rules = rules;
    library = new BoardLibrary();
    itemList = new UndoableObjects();
    components = new Components();
    this.communication = communication;
    this.boundingBox = boundingBox;
    searchTreeManager = new SearchTreeManager(this);
    rules.nets.setBoard(this);
    insertOutline(outlineShapes, outlineClClassNo);
  }

  /** Deserialize. */
  public static BasicBoard deserialize(byte[] objectByteArray) {
    try {
      ByteArrayInputStream inputStream = new ByteArrayInputStream(objectByteArray);
      ObjectInputStream objectStream = new ObjectInputStream(inputStream);

      return (BasicBoard) objectStream.readObject();
    } catch (Exception e) {
      FRLogger.error("Couldn't deserialize board", e);
    }

    return null;
  }

  private static String convertByteArrayToHexString(byte[] arrayBytes) {
    StringBuilder stringBuffer = new StringBuilder();
    for (int i = 0; i < arrayBytes.length; i++) {
      stringBuffer.append(Integer.toString((arrayBytes[i] & 0xff) + 0x100, 16).substring(1));
    }
    return stringBuffer.toString();
  }

  private static boolean isItemActivityDebugCandidate(Item item) {
    IntBox bounds = item.boundingBox();
    IntBox debugWindow = new IntBox(1620000, -1105000, 1930000, -1003000);
    return bounds != null && bounds.intersects(debugWindow);
  }

  private static String firstNetOrNone(Item item) {
    return item.netCount() > 0 ? Integer.toString(item.getNetNo(0)) : "none";
  }

  private static String describeBounds(IntBox bounds) {
    if (bounds == null) {
      return "null";
    }
    return "[(" + bounds.ll.x + "," + bounds.ll.y + ")..(" + bounds.ur.x + "," + bounds.ur.y + ")]";
  }

  public int getRevision() {
    return revision;
  }

  /** Increment revision. */
  public void incrementRevision() {
    revision++;
  }

  /** Serialize. */
  public byte[] serialize(boolean basicProfile) {
    try {
      ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
      ObjectOutputStream objectStream = new ObjectOutputStream(outputStream);

      if (basicProfile) {
        objectStream.writeObject(this.getTraces());
        objectStream.writeObject(this.getVias());
        objectStream.writeObject(this.itemList);
      } else {
        objectStream.writeObject(this);
      }

      objectStream.close();

      return outputStream.toByteArray();
    } catch (Exception e) {
      FRLogger.error("Couldn't serialize board", e);
    }

    return null;
  }

  /** Clone. */
  @Override
  public BasicBoard clone() {
    return deserialize(this.serialize(false));
  }

  /** Returns an MD5 hash of the board trace state. */
  public String getHash() {
    try {
      MessageDigest digest = MessageDigest.getInstance("MD5");
      digest.update(this.serialize(true));
      byte[] hashedBytes = digest.digest();

      return convertByteArrayToHexString(hashedBytes);
    } catch (Exception e) {
      FRLogger.error("Couldn't calculate hash for board", e);
    }

    return null;
  }

  /** Returns the number of trace ID differences compared to another board. */
  public int diffTraces(BasicBoard compareTo) {
    int result = 0;
    HashSet<Integer> traceIds = new HashSet<>();
    for (Trace trace : this.getTraces()) {
      traceIds.add(trace.getIdNo());
    }

    for (Trace trace : compareTo.getTraces()) {
      if (!traceIds.contains(trace.getIdNo())) {
        result++;
      } else {
        traceIds.remove(trace.getIdNo());
      }
    }
    result += traceIds.size();

    return result;
  }

  /**
   * Inserts a trace into the board, whose geometry is described by a Polyline. p_clearance_class is
   * the index in the clearanceMatrix, which describes the required clearance restrictions to other
   * items. Because no internal cleaning of items is done, the new inserted item can be returned.
   */
  public PolylineTrace insertTraceWithoutCleaning(
      Polyline polyline,
      int layer,
      int halfWidth,
      int[] netNoArr,
      int clearanceClass,
      FixedState fixedState) {
    if (polyline.cornerCount() < 2) {
      return null;
    }
    PolylineTrace newTrace =
        new PolylineTrace(
            polyline, layer, halfWidth, netNoArr, clearanceClass, 0, 0, fixedState, this);
    if (newTrace.firstCorner().equals(newTrace.lastCorner())) {
      if (fixedState.ordinal() < FixedState.USER_FIXED.ordinal()) {
        return null;
      }
    }
    insertItem(newTrace);
    if (newTrace.netsNormal()) {
      maxTraceHalfWidth = Math.max(maxTraceHalfWidth, halfWidth);
      minTraceHalfWidth = Math.min(minTraceHalfWidth, halfWidth);
    }
    return newTrace;
  }

  /**
   * Inserts a trace into the board, whose geometry is described by a Polyline. p_clearance_class is
   * the index in the clearanceMatrix, which describes the required clearance restrictions to other
   * items.
   */
  public void insertTrace(
      Polyline polyline,
      int layer,
      int halfWidth,
      int[] netNoArr,
      int clearanceClass,
      FixedState fixedState) {
    PolylineTrace newTrace =
        insertTraceWithoutCleaning(
            polyline, layer, halfWidth, netNoArr, clearanceClass, fixedState);
    if (newTrace == null) {
      return;
    }
    IntOctagon clipShape = null;
    if (this instanceof RoutingBoard board) {
      ChangedArea changedArea = board.changedArea;
      if (changedArea != null) {
        clipShape = changedArea.getArea(layer);
      }
    }

    try {
      newTrace.normalize(clipShape);
    } catch (Exception e) {
      // Normalization can fail for geometrically degenerate trace segments (e.g. caused by
      // malformed input geometry or extreme routing situations). The segment is skipped and
      // the connection may remain unrouted. This is non-critical — other segments will continue.
      FRLogger.warn(
          "A trace segment could not be normalized and was skipped. "
              + "Affected net may have an unrouted connection. Cause: "
              + e.getMessage());
      FRLogger.debug("BasicBoard.insert_trace_segment: normalization exception detail: " + e);
    }
  }

  /**
   * Inserts a trace into the board, whose geometry is described by an array of points, and cleans
   * up the net.
   */
  public void insertTrace(
      Point[] points,
      int layer,
      int halfWidth,
      int[] netNoArr,
      int clearanceClass,
      FixedState fixedState) {
    for (int i = 0; i < points.length; i++) {
      if (!this.boundingBox.contains(points[i])) {
        FRLogger.warn("LayeredBoard.insert_trace: input point out of range");
      }
    }
    Polyline poly = new Polyline(points);
    insertTrace(poly, layer, halfWidth, netNoArr, clearanceClass, fixedState);
  }

  /**
   * Inserts a via into the board. p_attach_allowed indicates, if the via may overlap with smd pins
   * of the same net.
   */
  public Via insertVia(
      Padstack padstack,
      Point center,
      int[] netNoArr,
      int clearanceClass,
      FixedState fixedState,
      boolean attachAllowed) {
    Via newVia =
        new Via(padstack, center, netNoArr, clearanceClass, 0, 0, fixedState, attachAllowed, this);
    insertItem(newVia);
    int fromLayer = padstack.fromLayer();
    int toLayer = padstack.toLayer();
    for (int i = fromLayer; i < toLayer; i++) {
      for (int currentNetNo : netNoArr) {
        splitTraces(center, i, currentNetNo);
      }
    }
    return newVia;
  }

  /**
   * Inserts a special escape via into the board for the fanout escalation phase. An escape via sits
   * directly on top of an SMD pin to provide a layer transition to an inner routing layer. On the
   * SMD layer it uses SMD-to-SMD clearance rules (because its copper is inside the SMD pad
   * footprint); on inner layers it uses normal via clearance.
   *
   * @param padstack The padstack describing the via geometry
   * @param center The center point (at the SMD pin center)
   * @param netNoArr The net numbers
   * @param clearanceClass The clearance class to use
   * @param fixedState The fixed state
   * @param smdLayer The SMD layer where the pin lives (clearance exception layer)
   */
  public Via insertEscapeVia(
      Padstack padstack,
      Point center,
      int[] netNoArr,
      int clearanceClass,
      FixedState fixedState,
      int smdLayer) {
    Via newVia = new Via(padstack, center, netNoArr, clearanceClass, 0, 0, fixedState, true, this);
    newVia.isEscapeVia = true;
    newVia.escapeViaSmdLayer = smdLayer;
    insertItem(newVia);
    int fromLayer = padstack.fromLayer();
    int toLayer = padstack.toLayer();
    for (int i = fromLayer; i <= toLayer; i++) {
      for (int currentNetNo : netNoArr) {
        splitTraces(center, i, currentNetNo);
      }
    }
    return newVia;
  }

  /**
   * Inserts a pin into the board. p_pin_no is the number of this pin in the library package of its
   * component (starting with 0).
   */
  public Pin insertPin(
      int componentNo, int pinNo, int[] netNoArr, int clearanceClass, FixedState fixedState) {
    Pin newPin = new Pin(componentNo, pinNo, netNoArr, clearanceClass, 0, fixedState, this);
    insertItem(newPin);
    return newPin;
  }

  /**
   * Inserts an obstacle into the board , whose geometry is described by a polygonal shape, which
   * may have holes. If p_component_no != 0, the obstacle belongs to a component.
   */
  public ObstacleArea insertObstacle(
      Area area, int layer, int clearanceClass, FixedState fixedState) {
    if (area == null) {
      FRLogger.warn("BasicBoard.insert_obstacle: p_area is null");
      return null;
    }
    ObstacleArea obs =
        new ObstacleArea(
            area, layer, Vector.ZERO, 0, false, clearanceClass, 0, 0, null, fixedState, this);
    insertItem(obs);
    return obs;
  }

  /**
   * Inserts an obstacle belonging to a component into the board p_name is to identify the
   * corresponding ObstacleArea in the component package.
   */
  public ObstacleArea insertObstacle(
      Area area,
      int layer,
      Vector translation,
      double rotationInDegree,
      boolean sideChanged,
      int clearanceClass,
      int componentNo,
      String name,
      FixedState fixedState) {
    if (area == null) {
      FRLogger.warn("BasicBoard.insert_obstacle: p_area is null");
      return null;
    }
    ObstacleArea obs =
        new ObstacleArea(
            area,
            layer,
            translation,
            rotationInDegree,
            sideChanged,
            clearanceClass,
            0,
            componentNo,
            name,
            fixedState,
            this);
    insertItem(obs);
    return obs;
  }

  /**
   * Inserts a via obstacle area into the board , whose geometry is described by a polygonal shape,
   * which may have holes.
   */
  public ViaObstacleArea insertViaObstacle(
      Area area, int layer, int clearanceClass, FixedState fixedState) {
    if (area == null) {
      FRLogger.warn("BasicBoard.insert_via_obstacle: p_area is null");
      return null;
    }
    ViaObstacleArea obs =
        new ViaObstacleArea(
            area, layer, Vector.ZERO, 0, false, clearanceClass, 0, 0, null, fixedState, this);
    insertItem(obs);
    return obs;
  }

  /**
   * Inserts a via obstacle belonging to a component into the board p_name is to identify the
   * corresponding ObstacleArea in the component package.
   */
  public ViaObstacleArea insertViaObstacle(
      Area area,
      int layer,
      Vector translation,
      double rotationInDegree,
      boolean sideChanged,
      int clearanceClass,
      int componentNo,
      String name,
      FixedState fixedState) {
    if (area == null) {
      FRLogger.warn("BasicBoard.insert_via_obstacle: p_area is null");
      return null;
    }
    ViaObstacleArea obs =
        new ViaObstacleArea(
            area,
            layer,
            translation,
            rotationInDegree,
            sideChanged,
            clearanceClass,
            0,
            componentNo,
            name,
            fixedState,
            this);
    insertItem(obs);
    return obs;
  }

  /**
   * Inserts a component obstacle area into the board , whose geometry is described by a polygonal
   * shape, which may have holes.
   */
  public ComponentObstacleArea insertComponentObstacle(
      Area area, int layer, int clearanceClass, FixedState fixedState) {
    if (area == null) {
      FRLogger.warn("BasicBoard.insert_component_obstacle: p_area is null");
      return null;
    }
    ComponentObstacleArea obs =
        new ComponentObstacleArea(
            area, layer, Vector.ZERO, 0, false, clearanceClass, 0, 0, null, fixedState, this);
    insertItem(obs);
    return obs;
  }

  /**
   * Inserts a component obstacle belonging to a component into the board. p_name is to identify the
   * corresponding ObstacleArea in the component package.
   */
  public ComponentObstacleArea insertComponentObstacle(
      Area area,
      int layer,
      Vector translation,
      double rotationInDegree,
      boolean sideChanged,
      int clearanceClass,
      int componentNo,
      String name,
      FixedState fixedState) {
    if (area == null) {
      FRLogger.warn("BasicBoard.insert_component_obstacle: p_area is null");
      return null;
    }
    ComponentObstacleArea obs =
        new ComponentObstacleArea(
            area,
            layer,
            translation,
            rotationInDegree,
            sideChanged,
            clearanceClass,
            0,
            componentNo,
            name,
            fixedState,
            this);
    insertItem(obs);
    return obs;
  }

  /** Inserts a component outline into the board. */
  public ComponentOutline insertComponentOutline(
      Area area,
      boolean isFront,
      Vector translation,
      double rotationInDegree,
      int componentNo,
      boolean isCourtyard,
      boolean isFabrication,
      boolean isClosed,
      FixedState fixedState) {
    if (area == null) {
      FRLogger.warn("BasicBoard.insert_component_outline: p_area is null");
      return null;
    }
    if (!area.isBounded()) {
      FRLogger.warn("BasicBoard.insert_component_outline: p_area is not bounded");
      return null;
    }
    ComponentOutline outline =
        new ComponentOutline(
            area,
            isFront,
            translation,
            rotationInDegree,
            0,
            componentNo,
            isCourtyard,
            isFabrication,
            isClosed,
            fixedState,
            this);
    insertItem(outline);
    return outline;
  }

  /**
   * Inserts a conduction area into the board , whose geometry is described by a polygonal shape,
   * which may have holes. If p_is_obstacle is false, it is possible to route through the conduction
   * area with traces and vias of foreign nets.
   */
  public ConductionArea insertConductionArea(
      Area area,
      int layer,
      int[] netNoArr,
      int clearanceClass,
      boolean isObstacle,
      FixedState fixedState) {
    if (area == null) {
      FRLogger.warn("BasicBoard.insert_conduction_area: p_area is null");
      return null;
    }
    ConductionArea c =
        new ConductionArea(
            area,
            layer,
            Vector.ZERO,
            0,
            false,
            netNoArr,
            clearanceClass,
            0,
            0,
            null,
            isObstacle,
            fixedState,
            this);
    insertItem(c);
    return c;
  }

  /** Inserts an Outline into the board. */
  public BoardOutline insertOutline(PolylineShape[] outlineShapes, int clearanceClassNo) {
    BoardOutline result = new BoardOutline(outlineShapes, clearanceClassNo, 0, this);
    insertItem(result);
    return result;
  }

  /** Returns the outline of the board. */
  public BoardOutline getOutline() {
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      UndoableObjects.Storable currentItem = itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof BoardOutline outline) {
        return outline;
      }
    }
    return null;
  }

  /** Removes an item from the board. */
  public void removeItem(Item item) {
    if (item == null) {
      return;
    }
    if (isItemActivityDebugCandidate(item)) {
      FRLogger.trace(
          "ITEM_ACTIVITY action=REMOVE"
              + ", id="
              + item.getIdNo()
              + ", type="
              + item.getClass().getSimpleName()
              + ", bounds="
              + describeBounds(item.boundingBox())
              + ", net0="
              + firstNetOrNone(item));
    }
    if (item instanceof Trace t && t.netNoArr.length > 0 && t.netNoArr[0] == 94) {
      if (t instanceof PolylineTrace pt
          && pt.cornerCount() == 2
          && t.firstCorner().equals(new app.freerouting.geometry.planar.IntPoint(1885928, -1097274))
          && t.lastCorner()
              .equals(new app.freerouting.geometry.planar.IntPoint(1885928, -1098024))) {
        FRLogger.trace(
            "BasicBoard.remove_item",
            "compare_trace_remove_item",
            "REMOVE_ITEM called on trace [7,8]",
            "Net #" + t.netNoArr[0] + ",Trace #" + t.getIdNo() + ",Layer #" + t.getLayer(),
            new Point[] {t.firstCorner(), t.lastCorner()});
        for (StackTraceElement ste : Thread.currentThread().getStackTrace()) {
          FRLogger.trace(
              "BasicBoard.remove_item",
              "compare_trace_remove_item_stack",
              ste.toString(),
              "Net #" + t.netNoArr[0] + ",Trace #" + t.getIdNo() + ",Layer #" + t.getLayer(),
              new Point[] {t.firstCorner(), t.lastCorner()});
        }
      } else {
        FRLogger.trace(
            "BasicBoard.remove_item",
            "compare_trace_remove_item",
            "REMOVE_ITEM called by " + Thread.currentThread().getStackTrace()[3],
            "Net #" + t.netNoArr[0] + ",Trace #" + t.getIdNo() + ",Layer #" + t.getLayer(),
            new Point[] {t.firstCorner(), t.lastCorner()});
      }
    }
    if (item.isDeletionForbidden()) {
      return;
    }
    additionalUpdateAfterChange(item); // must be called before p_item is deleted.
    searchTreeManager.remove(item);
    itemList.delete(item);

    // let the observers synchronize the deletion
    if ((communication != null) && (communication.observers != null)) {
      communication.observers.notifyDeleted(item);
    }
    incrementRevision();
  }

  /**
   * Searches for an item with the specified id number on the board.
   *
   * @param idNo the id number of the item to search for
   * @return the found item, or null if no such item is found
   */
  public Item getItem(int idNo) {
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      Item currentItem = (Item) itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem.getIdNo() == idNo) {
        return currentItem;
      }
    }
    return null;
  }

  /** Returns the list of all items on the board. */
  public Collection<Item> getItems() {
    Collection<Item> result = new LinkedList<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      Item currentItem = (Item) itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      result.add(currentItem);
    }
    return result;
  }

  /** Returns all connectable items on the board containing p_net_no. */
  public Collection<Item> getConnectableItems(int netNo) {
    Collection<Item> result = new LinkedList<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      Item currentItem = (Item) itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof Connectable && currentItem.containsNet(netNo)) {
        result.add(currentItem);
      }
    }
    return result;
  }

  /** Returns the count of connectable items of the net with number p_net_no. */
  public int connectableItemCount(int netNo) {
    int result = 0;
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      Item currentItem = (Item) itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof Connectable && currentItem.containsNet(netNo)) {
        ++result;
      }
    }
    return result;
  }

  /** Returns all items with the input component number. */
  public Collection<Item> getComponentItems(int componentNo) {
    Collection<Item> result = new LinkedList<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      Item currentItem = (Item) itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem.getComponentNo() == componentNo) {
        result.add(currentItem);
      }
    }
    return result;
  }

  /** Returns all pins with the input component number. */
  public Collection<Pin> getComponentPins(int componentNo) {
    Collection<Pin> result = new LinkedList<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      Item currentItem = (Item) itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem.getComponentNo() == componentNo && currentItem instanceof Pin pin) {
        result.add(pin);
      }
    }
    return result;
  }

  /**
   * Returns the pin with the input component number and pin number, or null, if no such pin exists.
   */
  public Pin getPin(int componentNo, int pinNo) {
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      Item currentItem = (Item) itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem.getComponentNo() == componentNo && currentItem instanceof Pin currentPin) {
        if (currentPin.pinNo == pinNo) {
          return currentPin;
        }
      }
    }
    return null;
  }

  /**
   * Removes the items in p_item_list. Returns false, if some items could not be removed, because
   * they are fixed.
   */
  public boolean removeItems(Collection<Item> itemList) {
    boolean result = true;
    for (Item currentItem : itemList) {
      if (currentItem.isDeletionForbidden() || currentItem.isUserFixed()) {
        // We are not allowed to delete this item
        result = false;
      } else {
        removeItem(currentItem);
      }
    }
    return result;
  }

  /** Returns the list of all conduction areas on the board. */
  public Collection<ConductionArea> getConductionAreas() {
    Collection<ConductionArea> result = new LinkedList<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      UndoableObjects.Storable currentItem = itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof ConductionArea area) {
        result.add(area);
      }
    }
    return result;
  }

  /** Returns the list of all pins on the board. */
  public Collection<Pin> getPins() {
    Collection<Pin> result = new LinkedList<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      UndoableObjects.Storable currentItem = itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof Pin pin) {
        result.add(pin);
      }
    }
    return result;
  }

  /** Returns the list of all pins on the board with only 1 layer. */
  public Collection<Pin> getSmdPins() {
    Collection<Pin> result = new LinkedList<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      UndoableObjects.Storable currentItem = itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof Pin currentPin) {
        if (currentPin.firstLayer() == currentPin.lastLayer()) {
          result.add(currentPin);
        }
      }
    }
    return result;
  }

  /** Returns the list of all vias on the board. */
  public Collection<Via> getVias() {
    Collection<Via> result = new LinkedList<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      UndoableObjects.Storable currentItem = itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof Via via) {
        result.add(via);
      }
    }
    return result;
  }

  /** Returns the list of all traces on the board. */
  public Collection<Trace> getTraces() {
    Collection<Trace> result = new LinkedList<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      UndoableObjects.Storable currentItem = itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof Trace trace) {
        result.add(trace);
      }
    }
    return result;
  }

  /** Returns the cumulative length of all traces on the board. */
  public double cumulativeTraceLength() {
    double result = 0;
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      UndoableObjects.Storable currentItem = itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof Trace trace) {
        result += trace.getLength();
      }
    }
    return result;
  }

  /**
   * Combines the connected traces of this net, which have only 1 contact at the connection point.
   * if p_net_no {@literal <} 0 traces of all nets are combined.
   */
  public boolean combineTraces(int netNo) {
    boolean result = false;
    boolean somethingChanged = true;
    while (somethingChanged) {
      somethingChanged = false;
      Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
      for (; ; ) {
        Item currentItem = (Item) itemList.readObject(it);
        if (currentItem == null) {
          break;
        }
        if ((netNo < 0 || currentItem.containsNet(netNo))
            && currentItem instanceof Trace trace
            && currentItem.isOnTheBoard()) {
          if (trace.combine()) {
            somethingChanged = true;
            result = true;
            break;
          }
        }
      }
    }
    return result;
  }

  /** Normalizes the traces of this net. */
  public boolean normalizeTraces(int netNo) {
    if (normalizeSuppressedNetNos == null) {
      normalizeSuppressedNetNos = new HashSet<>();
    }
    if (normalizeSuppressedNetNos.contains(netNo)) {
      String netName =
          rules != null && rules.nets != null && rules.nets.get(netNo) != null
              ? rules.nets.get(netNo).name
              : String.valueOf(netNo);
      FRLogger.debug(
          "BasicBoard.normalize_traces: skipping net '"
              + netName
              + "' because normalization already hit the oscillation cap on this board candidate.");
      return false;
    }
    boolean result = false;
    boolean somethingChanged = true;
    int iterationCount = 0;
    while (somethingChanged) {
      if (++iterationCount > MAX_NORMALIZE_ITERATIONS) {
        // Safety valve: after this many passes the outer loop has not converged.
        // This can happen when a pair of traces keeps oscillating between a split state
        // and a re-combined state (e.g. a self-intersecting or zero-length segment that
        // the geometry engine cannot cleanly normalise).  Stop here rather than hanging
        // the board-load thread for minutes.
        String netName =
            rules != null && rules.nets != null && rules.nets.get(netNo) != null
                ? rules.nets.get(netNo).name
                : String.valueOf(netNo);
        FRLogger.warn(
            "BasicBoard.normalize_traces: reached "
                + MAX_NORMALIZE_ITERATIONS
                + " iterations for net '"
                + netName
                + "' — stopping to prevent hang."
                + " The board geometry for this net may be oscillating (split/combine cycle);"
                + " traces are kept as-is and further normalization for this net is suppressed"
                + " on this board candidate.");
        normalizeSuppressedNetNos.add(netNo);
        break;
      }
      somethingChanged = false;

      // Collect traces for this net on this iteration to avoid ConcurrentModificationException
      // on the board's itemList during iteration, and to avoid scanning the entire board
      // repeatedly.
      java.util.List<PolylineTrace> netTraces = new java.util.ArrayList<>();
      Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
      for (; ; ) {
        Item currentItem;
        try {
          currentItem = (Item) itemList.readObject(it);
        } catch (ConcurrentModificationException _) {
          // If the board's item list was modified during collection (should be rare during
          // collection itself),
          // set somethingChanged to true to retry from a fresh state.
          somethingChanged = true;
          break;
        }
        if (currentItem == null) {
          break;
        }
        if (currentItem.containsNet(netNo)
            && currentItem instanceof PolylineTrace currentTrace
            && currentItem.isOnTheBoard()) {
          netTraces.add(currentTrace);
        }
      }

      if (somethingChanged) {
        continue;
      }

      for (PolylineTrace currentTrace : netTraces) {
        if (currentTrace.isOnTheBoard()) {
          if (currentTrace.normalize(null)) {
            somethingChanged = true;
            result = true;
          } else if (!currentTrace.isUserFixed() && this.removeIfCycle(currentTrace)) {
            somethingChanged = true;
            result = true;
          }
        }
      }
    }
    return result;
  }

  /** Normalizes the traces of all nets on the board in a single optimized pass. */
  public boolean normalizeAllTraces() {
    boolean result = false;
    // Group all PolylineTrace items by net
    java.util.Map<Integer, java.util.List<PolylineTrace>> tracesByNet = new java.util.HashMap<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      Item currentItem;
      try {
        currentItem = (Item) itemList.readObject(it);
      } catch (java.util.ConcurrentModificationException _) {
        // Retry collection if modified
        tracesByNet.clear();
        it = itemList.startReadObject();
        continue;
      }
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof PolylineTrace currentTrace && currentItem.isOnTheBoard()) {
        for (int netNo : currentTrace.netNoArr) {
          tracesByNet.computeIfAbsent(netNo, k -> new java.util.ArrayList<>()).add(currentTrace);
        }
      }
    }

    for (java.util.Map.Entry<Integer, java.util.List<PolylineTrace>> entry :
        tracesByNet.entrySet()) {
      int netNo = entry.getKey();
      java.util.List<PolylineTrace> netTraces = entry.getValue();
      boolean somethingChanged = true;
      int iterationCount = 0;
      while (somethingChanged) {
        if (++iterationCount > MAX_NORMALIZE_ITERATIONS) {
          String netName =
              rules != null && rules.nets != null && rules.nets.get(netNo) != null
                  ? rules.nets.get(netNo).name
                  : String.valueOf(netNo);
          FRLogger.warn(
              "BasicBoard.normalize_all_traces: reached "
                  + MAX_NORMALIZE_ITERATIONS
                  + " iterations for net '"
                  + netName
                  + "' — stopping to prevent hang.");
          break;
        }
        somethingChanged = false;

        for (PolylineTrace currentTrace : netTraces) {
          if (currentTrace.isOnTheBoard()) {
            if (currentTrace.normalize(null)) {
              somethingChanged = true;
              result = true;
            } else if (!currentTrace.isUserFixed() && this.removeIfCycle(currentTrace)) {
              somethingChanged = true;
              result = true;
            }
          }
        }

        // If something changed, collect the traces for this net again
        if (somethingChanged) {
          netTraces.clear();
          Iterator<UndoableObjects.UndoableObjectNode> it2 = itemList.startReadObject();
          for (; ; ) {
            Item currentItem;
            try {
              currentItem = (Item) itemList.readObject(it2);
            } catch (java.util.ConcurrentModificationException _) {
              netTraces.clear();
              it2 = itemList.startReadObject();
              continue;
            }
            if (currentItem == null) {
              break;
            }
            if (currentItem.containsNet(netNo)
                && currentItem instanceof PolylineTrace currentTrace
                && currentItem.isOnTheBoard()) {
              netTraces.add(currentTrace);
            }
          }
        }
      }
    }
    return result;
  }

  /**
   * Looks for traces of the input net on the input layer, so that p_location is on the trace
   * polygon, and splits these traces. Returns false, if no trace was split.
   */
  public boolean splitTraces(Point location, int layer, int netNo) {
    ItemSelectionFilter filter =
        new ItemSelectionFilter(ItemSelectionFilter.SelectableChoices.TRACES);
    Collection<Item> pickedItems = this.pickItems(location, layer, filter);
    IntOctagon locationShape = TileShape.getInstance(location).boundingOctagon();
    boolean traceSplit = false;
    for (Item currentItem : pickedItems) {
      Trace currentTrace = (Trace) currentItem;
      if (currentTrace.containsNet(netNo)) {
        Collection<PolylineTrace> splitPieces = currentTrace.split(locationShape);
        if (splitPieces.size() != 1) {
          traceSplit = true;
        }
      }
    }
    return traceSplit;
  }

  /** Returns a Collection of Collections of items forming a connected set. */
  public Collection<Collection<Item>> getConnectedSets(int netNo) {
    Collection<Collection<Item>> result = new LinkedList<>();
    if (netNo <= 0) {
      return result;
    }
    SortedSet<Item> itemsToHandle = new TreeSet<>();
    Iterator<UndoableObjects.UndoableObjectNode> it = this.itemList.startReadObject();
    for (; ; ) {
      Item currentItem = (Item) itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof Connectable && currentItem.containsNet(netNo)) {
        itemsToHandle.add(currentItem);
      }
    }
    Iterator<Item> it2 = itemsToHandle.iterator();
    while (it2.hasNext()) {
      Item currentItem = it2.next();
      Collection<Item> nextConnectedSet = currentItem.getConnectedSet(netNo);
      result.add(nextConnectedSet);
      itemsToHandle.removeAll(nextConnectedSet);
      it2 = itemsToHandle.iterator();
    }
    return result;
  }

  /**
   * Returns all SearchTreeObjects on layer p_layer, which overlap with p_shape. If p_layer
   * {@literal <} 0, the layer is ignored
   */
  public Set<SearchTreeObject> overlappingObjects(ConvexShape shape, int layer) {
    return this.searchTreeManager.getDefaultTree().overlappingObjects(shape, layer);
  }

  /**
   * Returns items, which overlap with p_shape on layer p_layer inclusive clearance.
   * p_clearance_class is the index in the clearance matrix, which describes the required clearance
   * restrictions to other items. The function may also return items, which are nearly overlapping,
   * but do not overlap with exact calculation. If p_layer {@literal <} 0, the layer is ignored.
   */
  public Set<Item> overlappingItemsWithClearance(
      ConvexShape shape, int layer, int[] ignoreNetNos, int clearanceClass) {
    ShapeSearchTree defaultTree = this.searchTreeManager.getDefaultTree();
    return defaultTree.overlappingItemsWithClearance(shape, layer, ignoreNetNos, clearanceClass);
  }

  /**
   * Returns all items on layer p_layer, which overlap with p_area. If p_layer {@literal <} 0, the
   * layer is ignored
   */
  public Set<Item> overlappingItems(Area area, int layer) {
    Set<Item> result = new TreeSet<>();
    TileShape[] tileShapes = area.splitToConvex();
    for (int i = 0; i < tileShapes.length; i++) {
      Set<SearchTreeObject> currentOverlaps = overlappingObjects(tileShapes[i], layer);
      for (SearchTreeObject currentOverlap : currentOverlaps) {
        if (currentOverlap instanceof Item item) {
          result.add(item);
        }
      }
    }
    return result;
  }

  /**
   * Checks, if an object with shape p_shape and net nos p_net_no_arr and clearance class p_cl_class
   * can be inserted on layer p_layer without clearance violation.
   */
  public boolean checkShape(Area shape, int layer, int[] netNoArr, int clClass) {
    TileShape[] tiles = shape.splitToConvex();
    ShapeSearchTree defaultTree = this.searchTreeManager.getDefaultTree();
    for (int i = 0; i < tiles.length; i++) {
      TileShape currentShape = tiles[i];
      if (!currentShape.isContainedIn(boundingBox)) {
        return false;
      }
      Set<SearchTreeObject> obstacles = new TreeSet<>();
      defaultTree.overlappingObjectsWithClearance(
          currentShape, layer, netNoArr, clClass, obstacles);
      for (SearchTreeObject currentOb : obstacles) {
        boolean isObstacle = true;
        for (int j = 0; j < netNoArr.length; j++) {
          if (!currentOb.isObstacle(netNoArr[j])) {
            isObstacle = false;
          }
        }
        if (isObstacle) {
          return false;
        }
      }
    }
    return true;
  }

  /**
   * Checks, if a trace line with shape p_shape and net numbers p_net_no_arr and clearance class
   * p_cl_class can be inserted on layer p_layer without clearance violation. If p_contact_pins !=
   * null, all pins not contained in p_contact_pins are regarded as obstacles, even if they are of
   * the own net.
   */
  public boolean checkTraceShape(
      TileShape shape, int layer, int[] netNoArr, int clClass, Set<Pin> contactPins) {
    if (!shape.isContainedIn(boundingBox)) {
      return false;
    }
    ShapeSearchTree defaultTree = this.searchTreeManager.getDefaultTree();
    Collection<TreeEntry> treeEntries = new LinkedList<>();
    int[] ignoreNetNos = new int[0];
    if (defaultTree.isClearanceCompensationUsed()) {
      defaultTree.overlappingTreeEntries(shape, layer, ignoreNetNos, treeEntries);
    } else {
      defaultTree.overlappingTreeEntriesWithClearance(
          shape, layer, ignoreNetNos, clClass, treeEntries);
    }
    for (TreeEntry currentTreeEntry : treeEntries) {
      if (!(currentTreeEntry.object instanceof Item currentItem)) {
        continue;
      }
      if (contactPins != null) {
        if (contactPins.contains(currentItem)) {
          continue;
        }
        if (currentItem instanceof Pin) {
          // The contact pins of the trace should be contained in p_ignore_items.
          // Other pins are handled as obstacles to avoid acid traps.
          return false;
        }
      }
      boolean isObstacle = true;
      for (int i = 0; i < netNoArr.length; i++) {
        if (!currentItem.isTraceObstacle(netNoArr[i])) {
          isObstacle = false;
        }
      }
      if (isObstacle && (currentItem instanceof PolylineTrace) && contactPins != null) {
        // check for traces of foreign nets at tie pins, which will be ignored inside
        // the pin shape
        TileShape intersection = null;
        for (Pin currentContactPin : contactPins) {
          if (currentContactPin.netCount() <= 1 || !currentContactPin.sharesNet(currentItem)) {
            continue;
          }
          if (intersection == null) {
            TileShape obstacleTraceShape =
                currentItem.getTileShape(currentTreeEntry.shapeIndexInObject);
            intersection = shape.intersection(obstacleTraceShape);
          }
          TileShape pinShape = currentContactPin.getTileShapeOnLayer(layer);
          if (pinShape.containsApprox(intersection)) {
            isObstacle = false;
            break;
          }
        }
      }
      if (isObstacle) {
        return false;
      }
    }
    return true;
  }

  /**
   * Checks, if a polyline trace with the input parameters can be inserted without clearance.
   * violations
   */
  public boolean checkPolylineTrace(
      Polyline polyline, int layer, int penHalfWidth, int[] netNoArr, int clearanceClass) {
    Trace tmpTrace =
        new PolylineTrace(
            polyline,
            layer,
            penHalfWidth,
            netNoArr,
            clearanceClass,
            0,
            0,
            FixedState.UNFIXED,
            this);
    Set<Pin> contactPins = tmpTrace.touchingPinsAtEndCorners();
    for (int i = 0; i < tmpTrace.tileShapeCount(); i++) {
      if (!this.checkTraceShape(
          tmpTrace.getTileShape(i), layer, netNoArr, clearanceClass, contactPins)) {
        return false;
      }
    }
    return true;
  }

  /** Returns the layer count of this board. */
  public int getLayerCount() {
    return layerStructure.arr.length;
  }

  /**
   * Returns the list of items on the board, whose shape on layer p_layer contains the point at
   * p_location. If p_layer {@literal <} 0, the layer is ignored. If p_item_selection_filter !=
   * null, only items of types selected by the filter are picked.
   */
  public Set<Item> pickItems(Point location, int layer, ItemSelectionFilter filter) {
    TileShape pointShape = TileShape.getInstance(location);
    Collection<SearchTreeObject> overlaps = overlappingObjects(pointShape, layer);
    Set<Item> result = new TreeSet<>();
    for (SearchTreeObject currentObject : overlaps) {
      if (currentObject instanceof Item item) {
        result.add(item);
      }
    }
    if (filter != null) {
      result = filter.filter(result);
    }
    return result;
  }

  /** Checks, if p_point is contained in the bounding box of this board. */
  public boolean contains(Point point) {
    return point.isContainedIn(boundingBox);
  }

  /**
   * Returns the minimum clearance requested between items of clearance class p_class_1 and
   * p_class_2. p_class_1 and p_class_2 are indices in the clearance matrix.
   */
  public int clearanceValue(int class1, int class2, int layer) {
    if (rules == null || rules.clearanceMatrix == null) {
      return 0;
    }
    return rules.clearanceMatrix.getValue(class1, class2, layer, true);
  }

  /** Returns the biggest half width of all traces on the board. */
  public int getMaxTraceHalfWidth() {
    return maxTraceHalfWidth;
  }

  /** Returns the smallest half width of all traces on the board. */
  public int getMinTraceHalfWidth() {
    return minTraceHalfWidth;
  }

  /** Returns a surrounding box of the geometry of this board. */
  public IntBox getBoundingBox() {
    return boundingBox;
  }

  /** Returns a box containing all items in p_item_list. */
  public IntBox getBoundingBox(Collection<Item> itemList) {
    IntBox result = IntBox.EMPTY;
    for (Item currentItem : itemList) {
      result = result.union(currentItem.boundingBox());
    }
    return result;
  }

  /** Resets the rectangle, where a graphics update is needed. */
  public void resetGraphicsUpdateBox() {
    updateBox = IntBox.EMPTY;
  }

  /** Gets the rectangle, where a graphics update is needed on the screen. */
  public IntBox getGraphicsUpdateBox() {
    return updateBox;
  }

  /** Enlarges the graphics update box, so that it contains p_box. */
  public void joinGraphicsUpdateBox(IntBox box) {
    if (updateBox == null) {
      resetGraphicsUpdateBox();
    }
    updateBox = updateBox.union(box);
  }

  /** Starts notifying the observers of any change in the objects list. */
  public void startNotifyObservers() {
    if ((communication != null) && (this.communication.observers != null)) {
      communication.observers.activate();
    }
  }

  /** Ends notifying the observers of changes in the objects list. */
  public void endNotifyObservers() {
    if ((communication != null) && (this.communication.observers != null)) {
      communication.observers.deactivate();
    }
  }

  /** Returns, if the observer of the board items is activated. */
  public boolean observersActive() {
    boolean result;
    if ((communication != null) && (this.communication.observers != null)) {
      result = communication.observers.isActive();
    } else {
      result = false;
    }
    return result;
  }

  /**
   * Turns an obstacle area into a conduction area with net number p_net_no If it is convex and has
   * no holes, it is turned into a Pin, else into a conduction area.
   */
  public Connectable makeConductive(ObstacleArea area, int netNo) {
    Item newItem;
    Area currentArea = area.getRelativeArea();
    int layer = area.getLayer();
    FixedState fixedState = area.getFixedState();
    Vector translation = area.getTranslation();
    double rotation = area.getRotationInDegree();
    boolean sideChanged = area.getSideChanged();
    int[] netNoArr = new int[1];
    netNoArr[0] = netNo;
    newItem =
        new ConductionArea(
            currentArea,
            layer,
            translation,
            rotation,
            sideChanged,
            netNoArr,
            area.clearanceClassNo(),
            0,
            area.getComponentNo(),
            area.name,
            true,
            fixedState,
            this);
    removeItem(area);
    insertItem(newItem);
    return (Connectable) newItem;
  }

  /** Inserts an item into the board database. */
  public void insertItem(Item item) {
    if (item == null) {
      return;
    }
    if (isItemActivityDebugCandidate(item)) {
      FRLogger.trace(
          "ITEM_ACTIVITY action=INSERT"
              + ", id="
              + item.getIdNo()
              + ", type="
              + item.getClass().getSimpleName()
              + ", bounds="
              + describeBounds(item.boundingBox())
              + ", net0="
              + firstNetOrNone(item));
    }

    if (rules == null
        || rules.clearanceMatrix == null
        || item.clearanceClassNo() < 0
        || item.clearanceClassNo() >= rules.clearanceMatrix.getClassCount()) {
      FRLogger.warn("LayeredBoard.insert_item: clearanceClass no out of range");
      item.setClearanceClassNo(0);
    }
    item.board = this;
    itemList.insert(item);
    searchTreeManager.insert(item);
    if ((communication != null) && (communication.observers != null)) {
      communication.observers.notifyNew(item);
    }
    additionalUpdateAfterChange(item);
    incrementRevision();
  }

  /**
   * Stub function overwritten in class RoutingBoard to maintain the autorouter database if
   * necessary.
   */
  public void additionalUpdateAfterChange(Item item) {}

  /**
   * Restores the situation at the previous snapshot. Returns false, if no more undo is possible.
   * Puts the numbers of the changed nets into the set p_changed_nets, if p_changed_nets != null
   */
  public boolean undo(Set<Integer> changedNets) {
    this.components.undo(this.communication.observers);
    Collection<UndoableObjects.Storable> cancelledObjects = new LinkedList<>();
    Collection<UndoableObjects.Storable> restoredObjects = new LinkedList<>();
    boolean result = itemList.undo(cancelledObjects, restoredObjects);
    applyUndoRedoSideEffects(cancelledObjects, restoredObjects, changedNets);
    return result;
  }

  /**
   * Restores the situation before the last undo. Returns false, if no more redo is possible. Puts
   * the numbers of the changed nets into the set p_changed_nets, if p_changed_nets != null
   */
  public boolean redo(Set<Integer> changedNets) {
    this.components.redo(this.communication.observers);
    Collection<UndoableObjects.Storable> cancelledObjects = new LinkedList<>();
    Collection<UndoableObjects.Storable> restoredObjects = new LinkedList<>();
    boolean result = itemList.redo(cancelledObjects, restoredObjects);
    applyUndoRedoSideEffects(cancelledObjects, restoredObjects, changedNets);
    return result;
  }

  private void applyUndoRedoSideEffects(
      Collection<UndoableObjects.Storable> cancelledObjects,
      Collection<UndoableObjects.Storable> restoredObjects,
      Set<Integer> changedNets) {
    Iterator<UndoableObjects.Storable> it = cancelledObjects.iterator();
    while (it.hasNext()) {
      Item currentItem = (Item) it.next();
      searchTreeManager.remove(currentItem);
      if ((communication != null) && (communication.observers != null)) {
        communication.observers.notifyDeleted(currentItem);
      }
      if (changedNets != null) {
        for (int i = 0; i < currentItem.netCount(); i++) {
          changedNets.add(currentItem.getNetNo(i));
        }
      }
    }
    it = restoredObjects.iterator();
    while (it.hasNext()) {
      Item currentItem = (Item) it.next();
      currentItem.board = this;
      searchTreeManager.insert(currentItem);
      currentItem.clearAutorouteInfo();
      if ((communication != null) && (communication.observers != null)) {
        communication.observers.notifyNew(currentItem);
      }
      if (changedNets != null) {
        for (int i = 0; i < currentItem.netCount(); i++) {
          changedNets.add(currentItem.getNetNo(i));
        }
      }
    }
  }

  /** Makes the current board situation restorable by undo. */
  public void generateSnapshot() {
    itemList.generateSnapshot();
    components.generateSnapshot();
  }

  /**
   * Removes the top snapshot from the undo stack, so that its situation cannot be restored anymore.
   * Returns false, if no more snapshot could be popped.
   */
  public boolean popSnapshot() {
    return itemList.popSnapshot();
  }

  /**
   * Looks if at the input position ends a trace with the input net number, which has no normal
   * contact at that position. Returns null, if no tail is found.
   */
  public Trace getTraceTail(Point location, int layer, int[] netNoArr) {
    TileShape pointShape = TileShape.getInstance(location);
    Collection<SearchTreeObject> foundItems = overlappingObjects(pointShape, layer);
    for (SearchTreeObject currentOb : foundItems) {
      if (currentOb instanceof Trace currentTrace) {
        if (!currentTrace.netsEqual(netNoArr)) {
          continue;
        }
        if (currentTrace.firstCorner().equals(location)) {
          Collection<Item> contacts = currentTrace.getStartContacts();
          if (contacts.isEmpty()) {
            return currentTrace;
          }
        }
        if (currentTrace.lastCorner().equals(location)) {
          Collection<Item> contacts = currentTrace.getEndContacts();
          if (contacts.isEmpty()) {
            return currentTrace;
          }
        }
      }
    }
    return null;
  }

  /**
   * Checks, if p_item item is part of a cycle and remove it together with its connection in this
   * case.
   */
  public boolean removeIfCycle(Trace trace) {
    if (!trace.isOnTheBoard()) {
      return false;
    }
    if (!trace.isCycle()) {
      return false;
    }
    // Remove tails at the endpoints after removing the cycle,
    // if there was no tail before.
    int currentLayer = trace.getLayer();
    int[] currentNetNoArr = trace.netNoArr;
    Point[] endCorners = new Point[2];
    endCorners[0] = trace.firstCorner();
    endCorners[1] = trace.lastCorner();
    boolean[] tailAtEndpointBefore = new boolean[2];
    for (int i = 0; i < 2; i++) {
      Trace tail = getTraceTail(endCorners[i], currentLayer, currentNetNoArr);
      tailAtEndpointBefore[i] = tail != null;
    }
    Set<Item> connectionItems = trace.getConnectionItems();
    this.removeItems(connectionItems);
    for (int i = 0; i < 2; i++) {
      if (!tailAtEndpointBefore[i]) {
        Trace tail = getTraceTail(endCorners[i], currentLayer, currentNetNoArr);
        if (tail != null) {
          removeItems(tail.getConnectionItems());
        }
      }
    }
    return true;
  }

  private void readObject(ObjectInputStream stream) throws IOException, ClassNotFoundException {
    stream.defaultReadObject();
    // insert the items on the board into the search trees
    searchTreeManager = new SearchTreeManager(this);
    normalizeSuppressedNetNos = new HashSet<>();
    for (Item currentItem : this.getItems()) {
      currentItem.board = this;
      searchTreeManager.insert(currentItem);
    }
  }

  /** Deletes all traces and vias from the board. */
  public void deleteAllTracksAndVias() {
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      UndoableObjects.Storable currentItem = itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof Trace) {
        // delete the trace
        itemList.delete(currentItem);
      }
      if (currentItem instanceof Via) {
        // delete the via
        itemList.delete(currentItem);
      }
    }
  }

  /**
   * Unfills all conduction zones on the board, leaving only their definitions (boundaries) visible.
   * This disables them as routing obstacles and prevents connection stubs from being routed to
   * them.
   */
  public void unfillConductionAreas() {
    this.rules.setIgnoreConduction(true);
    Iterator<UndoableObjects.UndoableObjectNode> it = itemList.startReadObject();
    for (; ; ) {
      UndoableObjects.Storable currentItem = itemList.readObject(it);
      if (currentItem == null) {
        break;
      }
      if (currentItem instanceof ConductionArea currentConductionArea) {
        currentConductionArea.setIsFilled(false);
        currentConductionArea.setIsObstacle(false);
      }
    }
    this.searchTreeManager.reinsertTreeItems();
  }

  /** Logs a warning if connectable items exist on inactive routing layers. */
  public void areThereItemsOnInactiveLayer(AutorouteControl ctrl) {
    if (this.getLayerCount() > 2) {
      boolean hasSomethingOnInactiveLayer = false;
      Iterator<UndoableObjects.UndoableObjectNode> it = this.itemList.startReadObject();
      for (; ; ) {
        UndoableObjects.Storable currentOb = this.itemList.readObject(it);
        if (currentOb == null) {
          break;
        }
        if (currentOb instanceof PolylineTrace currentItem) {
          // This is a connectable item, like PolylineTrace or Pin
          if (!ctrl.layerActive[currentItem.getLayer()]) {
            hasSomethingOnInactiveLayer = true;
            FRLogger.warn("There is an item on an inactive layer.");
            break;
          }
        }
      }
    }
  }

  /** Returns the number of traces that are not multiples of 45 degrees. */
  public int getNon45DegreeTraceCount() {
    int count = 0;
    for (Item currentOb : getItems()) {
      if (currentOb instanceof PolylineTrace currentTrace) {
        if (!currentTrace.polyline().isMultipleOf45Degree()) {
          ++count;
        }
      }
    }
    return count;
  }

  /**
   * Draws all items of the board on their visible layers. Called in the overwritten paintComponent
   * method of a class derived from JPanel. The value of p_layer_visibility is expected between 0
   * and 1 for each layer.
   */
  public enum DominantSide {
    FRONT,
    BACK,
    NONE
  }
}
