package app.freerouting.io.specctra.parser;

import java.io.IOException;

/** Interface for scanner generated by jflex. */
@SuppressWarnings({
  "checkstyle:AbbreviationAsWordInName",
  "checkstyle:MissingJavadocMethod",
  "checkstyle:MissingJavadocType"
})
public interface IJFlexScanner {

  /* Returns the current scope identifier. */
  String getScopeIdentifier();

  /* Sets the current scope identifier. */
  void setScopeIdentifier(String identifier);

  /** Reads the next token from the input file. */
  Object nextToken() throws IOException;

  /** Reads the next token as a string from the input file. */
  String nextString();

  String nextString(boolean ignoreNewline);

  String[] nextStringList();

  String[] nextStringList(char separator);

  /** Reads the next token as a double from the input file. */
  Double nextDouble();

  Boolean nextClosingBracket();

  /** Starts a new state. */
  void yybegin(int newState);
}
