package app.freerouting.designforms.specctra;

/** Interface for scanner generated by jflex. */
public interface IJFlexScanner {
  /** Reads the next token from the input file. */
  Object next_token() throws java.io.IOException;

  /** Reads the next token as a string from the input file. */
  String next_string();

  String next_string(boolean ignoreNewline);

  String[] next_string_list();

  String[] next_string_list(char separator);

  /** Reads the next token as a double from the input file. */
  Double next_double();

  Boolean next_closing_bracket();

  /** Starts a new state. */
  void yybegin(int p_new_state);
}
