<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!--generated by JHelpDev Version: 0.5, 2 October 2005, see jhelpdev.sourceforge.net--><!DOCTYPE helpset PUBLIC "-//Sun Microsystems Inc.//DTD JavaHelp HelpSet Version 2.0//EN" "http://java.sun.com/products/javahelp/helpset_2_0.dtd">

<helpset version="1.0">
 <title>Help </title>
 <maps>
  <homeID>
top
  </homeID>
  <mapref location="Map.jhm"/>

 </maps>
 <view>
  <name>
TOC
  </name>
  <label>
Contents 
  </label>
  <type>
javax.help.TOCView
  </type>
  <data>
HelpTOC.xml
  </data>
 </view>
 <view>
  <name>
Index
  </name>
  <label>
Index 
  </label>
  <type>
javax.help.IndexView
  </type>
  <data>
HelpIndex.xml
  </data>
 </view>
 <view>
  <name>
Search
  </name>
  <label>
Search 
  </label>
  <type>
javax.help.SearchView
  </type>
  <data engine="com.sun.java.help.search.DefaultSearchEngine">
JavaHelpSearch
  </data>
 </view>
</helpset>
