package eu.mihosoft.freerouting.designforms.specctra;

/**
 * Interface for scanner generated by jflex.
 */
public interface Scanner
{
    /**
     * Reads the next token from the input file.
     */
    Object next_token() throws java.io.IOException;
    
    /**
     * Starts a new state.
     */
    void yybegin(int p_new_state);
}
