name: 'Distribution: Snapshot Installers'

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows you to run this workflow manually

jobs:
  test:
    name: 'Test & Verify'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/help/legal-terms-of-use'
          build-scan-terms-of-use-agree: 'yes'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Run Tests
        run: ./gradlew build

  delete-old-snapshot-assets:
    runs-on: [ ubuntu-latest ]
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Delete old SNAPSHOT assets
        uses: mknejp/delete-release-assets@v1
        with:
          fail-if-no-assets: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: SNAPSHOT
          assets: |
            freerouting-SNAPSHOT.zip
            freerouting-SNAPSHOT.tar.gz
            freerouting-SNAPSHOT-*.*

  build-jar:
    name: 'Build JAR'
    needs: [ test, delete-old-snapshot-assets ]
    runs-on: [ ubuntu-latest ]
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/help/legal-terms-of-use'
          build-scan-terms-of-use-agree: 'yes'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Grant execute permission for build scripts
        run: chmod +x scripts/build/*.sh
      - name: Build with Gradle
        run: ./gradlew dist
      - name: Create Distribution
        run: scripts/build/create-distribution-jar.sh "SNAPSHOT-$(date +'%Y%m%d_%H%M00')"
      - uses: AButler/upload-release-assets@v4.0
        with:
          files: './scripts/build/freerouting-SNAPSHOT-*.jar'
          release-tag: SNAPSHOT
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu-x64:
    needs: [ test, delete-old-snapshot-assets ]
    runs-on: [ ubuntu-latest ]
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/help/legal-terms-of-use'
          build-scan-terms-of-use-agree: 'yes'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Grant execute permission for build scripts
        run: chmod +x scripts/build/*.sh
      - name: Build with Gradle
        run: ./gradlew dist
      - name: Create Distribution
        run: scripts/build/create-distribution-SNAPSHOT-linux-x64.sh SNAPSHOT-$(date +"%Y%m%d_%H%M00")
      - uses: AButler/upload-release-assets@v4.0
        with:
          files: './scripts/build/freerouting-SNAPSHOT-*-linux-x64.zip'
          release-tag: SNAPSHOT
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-windows-x64:
    needs: [ test, delete-old-snapshot-assets ]
    runs-on: [ windows-latest ]
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/help/legal-terms-of-use'
          build-scan-terms-of-use-agree: 'yes'
      - name: Build with Gradle
        run: .\gradlew.bat dist --no-daemon
      - name: Create Distribution
        run: .\scripts\build\create-distribution-SNAPSHOT-windows-x64.bat "SNAPSHOT-$(([datetime]::now).tostring("yyyyMMdd_HHmm00"))"
      - uses: AButler/upload-release-assets@v4.0
        with:
          files: './scripts/build/freerouting-SNAPSHOT-*-windows-x64.msi'
          release-tag: SNAPSHOT
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-macos-arm64:
    needs: [ test, delete-old-snapshot-assets ]
    runs-on: [ macos-15 ]
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/help/legal-terms-of-use'
          build-scan-terms-of-use-agree: 'yes'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Grant execute permission for build scripts
        run: chmod +x scripts/build/*.sh
      - name: Build with Gradle
        run: ./gradlew dist
      - name: Create Distribution
        run: scripts/build/create-distribution-SNAPSHOT-macos-arm64.sh SNAPSHOT-$(date +"%Y%m%d_%H%M00") "${{ secrets.APPLE_DEVELOPER_ID }}"
      - uses: AButler/upload-release-assets@v4.0
        with:
          files: './scripts/build/freerouting-SNAPSHOT-*-macos-arm64.dmg'
          release-tag: SNAPSHOT
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-macos-x64:
    needs: [ test, delete-old-snapshot-assets ]
    runs-on: [ macos-15-intel ]
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          architecture: 'x64'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/help/legal-terms-of-use'
          build-scan-terms-of-use-agree: 'yes'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Grant execute permission for build scripts
        run: chmod +x scripts/build/*.sh
      - name: Build with Gradle
        run: ./gradlew dist
      - name: Create Distribution
        run: scripts/build/create-distribution-SNAPSHOT-macos-x64.sh SNAPSHOT-$(date +"%Y%m%d_%H%M00") "${{ secrets.APPLE_DEVELOPER_ID }}"
      - uses: AButler/upload-release-assets@v4.0
        with:
          files: './scripts/build/freerouting-SNAPSHOT-*-macos-x64.dmg'
          release-tag: SNAPSHOT
          repo-token: ${{ secrets.GITHUB_TOKEN }}
